

describe('Pizza App', () => {

    beforeEach(() => {
        cy.visit('http://localhost:3000')
    })
    it('sanity check for making sure evertything is setup', () => {
        expect(1+1).to.equal(2)
    })
const nameInput = () => cy.get('#name-input')
const pizzaButton = () => cy.get('#order-pizza')
const addressInput = () => cy.get('input[name="address"]')
const emailInput = () => cy.get('input[name="email"]')
const phoneNumberInput = () => cy.get('input[name="phoneNumber"]')
const crustInput = () => cy.get('[type="radio"]')
const sizeDropDown = () => cy.get('#size-dropdown')
const toppingInput = () => cy.get('[type="checkbox"]')
const specialInput = () => cy.get('#special-text')
const addToOrderButton = () => cy.get('#order-button')

    it('can fill out form correctly and submit order', () => {
        pizzaButton()
            .click()
        nameInput()
            .should('have.value', '')
            .type('Test Name')
            .should('have.value', 'Test Name')
        addressInput()
            .should('have.value', '')
            .type('1234 test st')
            .should('have.value', '1234 test st')
        emailInput()
            .should('have.value', '')
            .type('test@test.com')
            .should('have.value', 'test@test.com')
        phoneNumberInput()
            .should('have.value', '')
            .type('123-456-7890')
            .should('have.value', '123-456-7890')
        crustInput()
            .should('not.be.checked')
            .check()
            .should('be.checked')
        sizeDropDown()
            .should('have.value', '')
            .select('small')
            .should('have.value', 'small')
        toppingInput()
            .should('not.be.checked')
            .check()
            .should('be.checked')
        specialInput()
            .should('have.value', '')
            .type('special instructions')
            .should('have.value', 'special instructions')
        addToOrderButton()
            .click()
    })

})